Offset for Eye-Focus
SillyTavern/Extension-Live2d pull request #5
Opened 2023-12-26 22:40 UTC by Baromeus

adds option to set the offset for the eye-focus (follow cursor) per character.

I added the option right below the others.

![image](https://github.com/SillyTavern/Extension-Live2d/assets/77576424/f07a693d-c84d-4ecc-86fc-3f0daed77fc3)

Also I changed the default values for PARAM_ANGLE_X and PARAM_ANGLE_Y  to the representative values.

**Information:**
I had some problems with Models that where already set - please try if this problem persists (I wasn't able to reproduce it)

2023-12-27 22:38 UTC, Tony-sama requested changes
A few corrections needed.

2023-12-27 22:38 UTC, Tony-sama commented on index.js
"live2d_model_param_mouth_form_01_select" id is not used, need to be removed.

2023-12-27 22:38 UTC, Tony-sama commented on live2d.js
"||-0.45" probably need to be normalized to 45 since convertion is done int the min.js file.

2023-12-27 22:38 UTC, Tony-sama commented on ui.js
Same -0.45 convertion needed.

2023-12-27 22:38 UTC, Tony-sama commented on window.html
"value="-45"" Default should be 45 in place of -45 I suppose :)

2023-12-28 11:12 UTC, Baromeus commented on index.js
fixed

2023-12-28 11:13 UTC, Baromeus commented on live2d.js
fixed

2023-12-28 11:15 UTC, Baromeus commented
Fixed the mentioned problems.

2023-12-28 16:03 UTC, merged